## Try 1

- Oversampling
- Param grid (see below)
- scoring = make_scorer(fbeta_score, beta=2)
- cv = 5 
- used 'consommation_per_month'

**Test ROC AUC Score: 0.5217537024317412**


#### Result


**Best Model/Best Params**

**Best score:**

0.99

**Best parameters:**

{'st__knn__weights': 'distance', 'st__knn__p': 1, 'st__knn__n_neighbors': 42, 'st__knn__algorithm': 'brute', 'st__dt__min_samples_split': 5, 'st__dt__max_leaf_nodes': 10, 'st__dt__max_features': 0.6, 'st__dt__max_depth': 15, 'st__class__penalty': 'l2', 'st__class__max_iter': 1000, 'st__class__loss': 'log_loss', 'st__class__learning_rate': 'constant', 'st__class__eta0': 0.01, 'st__class__alpha': 0.001}

**Test**

Test ROC AUC Score: 0.5217537024317412


||Negative_pred|Positive_pred|
|---|---|---|
|Negative|1018934|   11575|
|Positive|87140|    1073|



 
              precision    recall  f1-score   support

         0.0       0.92      0.99      0.95   1030509
         1.0       0.08      0.01      0.02     88213

    accuracy       ...       ...       0.91   1118722
    macro avg      0.50      0.50      0.49   1118722
    weighted avg   0.86      0.91      0.88   1118722


**Train**

Train ROC AUC Score: 0.999824613441643

||Negative_pred|Positive_pred|
|---|---|---|
|negative|126272|    116|
|positive|709| 125679|
 


              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00    126388
         1.0       1.00      0.99      1.00    126388

    accuracy                           1.00    252776
    macro avg      1.00      1.00      1.00    252776
    weighted avg   1.00      1.00      1.00    252776

#### Details

In [ ]:
param_st = {'st__dt__max_features': ['auto', 'sqrt', None] + list(np.arange(0.5, 1, 0.1)),
    'st__dt__max_leaf_nodes': [None] + list(np.arange(10, 51).astype(int)),
    'st__dt__min_samples_split': [2, 5, 10],
    'st__dt__max_depth': [None] + list(np.arange(3, 21).astype(int)),
    'st__knn__n_neighbors' : np.arange(2,50), #this actually defines the model you use
    'st__knn__weights' : ['uniform', 'distance'],
    'st__knn__p' : [1, 2, 3],
    'st__knn__algorithm': ['ball_tree', 'kd_tree', 'brute'],
    'st__class__penalty':('l1','l2'),
    'st__class__alpha': [0.001, 0.01, 0.1, 1, 10],
    'st__class__learning_rate': ['optimal', 'constant', 'invscaling'],
    'st__class__loss': ['log_loss', 'hinge', 'huber'],
    'st__class__max_iter' : [1000, 500],
    'st__class__eta0': [0.001, 0.01]
    }


## Try 2

- Changes: Undersampling (instead of oversampling)
- Feature Engineering: consommation_sum instead of consommation_per_month
- Imputing consommoation_sum = 0 with median value


**Test ROC AUC Score: 0.5090593874801974**


### Result

Best score:

0.22

Best parameters:

{'st__knn__weights': 'uniform', 'st__knn__p': 2, 'st__knn__n_neighbors': 32, 'st__knn__algorithm': 'ball_tree', 'st__dt__min_samples_split': 2, 'st__dt__max_leaf_nodes': 48, 'st__dt__max_features': 'sqrt', 'st__dt__max_depth': 9, 'st__class__penalty': 'l1', 'st__class__max_iter': 500, 'st__class__loss': 'log_loss', 'st__class__learning_rate': 'optimal', 'st__class__eta0': 0.001, 'st__class__alpha': 0.01}

**Test**

Test ROC AUC Score: 0.5090593874801974



||Negative_pred|Positive_pred|
|---|---|---|
|negative|969891 | 60618|
|positive| 82101  | 6112|

                   precision    recall  f1-score   support

         0.0       0.92         0.94      0.93     1030509
         1.0       0.09         0.07      0.08     88213

    accuracy                              0.87     1118722
    macro avg       0.51        0.51      0.51     1118722
    weighted avg    0.86        0.87      0.86     1118722

**Train**

Train ROC AUC Score: 0.7658545721235135


||Negative_pred|Positive_pred|
|---|---|---|
|negative| 88016 |38372|
|positive|2292 | 5260|


              precision    recall  f1-score   support

         0.0       0.97      0.70      0.81    126388
         1.0       0.12      0.70      0.21      7552

    accuracy                           0.70    133940
    macro avg      0.55      0.70      0.51    133940
    weighted avg   0.93      0.70      0.78    133940

----

## Try 3

- extended dataset
- undersampling (no pipeline)
- scorer: own scorer

**Test ROC AUC Score: 0.6169694532581234**

#### Results


**Test**

Test ROC AUC Score: 0.6169694532581234

[[12887 19081]

 [  434  1457]]


              precision    recall  f1-score   support

         0.0       0.97      0.40      0.57     31968
         1.0       0.07      0.77      0.13      1891

    accuracy                           0.42     33859
    macro avg      0.52      0.59      0.35     33859
    weighted avg   0.92      0.42      0.54     33859

**Train**


Train ROC AUC Score: 0.6682151081180718

[[39710 56190]

[ 1092  4582]]


              precision    recall  f1-score   support

         0.0       0.97      0.41      0.58     95900
         1.0       0.08      0.81      0.14      5674

    accuracy                           0.44    101574
    macro avg      0.52      0.61      0.36    101574
    weighted avg   0.92      0.44      0.56    101574

## Try 4

- extended dataset
- oversampling (no pipeline)
- scorer = roc_auc

**Test ROC AUC Score: 0.581422147954406**

#### Results

**Test**

Test ROC AUC Score: 0.581422147954406

[[30952  1016]

[ 1817    74]]


              precision    recall  f1-score   support

         0.0       0.94      0.97      0.96     31968
         1.0       0.07      0.04      0.05      1891

    accuracy                           0.92     33859
    macro avg      0.51      0.50      0.50     33859
    weighted avg   0.90      0.92      0.91     33859

**Train**

Train ROC AUC Score: 0.9999152109807639

[[95816    84]

[  349 95551]]


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     95900
         1.0       1.00      1.00      1.00     95900

    accuracy                           1.00    191800
    macro avg      1.00      1.00      1.00    191800
    weighted avg   1.00      1.00      1.00    191800

## Try 5

- extended dataset
- undersampling (no Pipe)
- scorere = roc_auc

**Test ROC AUC Score: 0.6174881501676186**

#### Results


**Test**



Test ROC AUC Score: 0.6174881501676186

[[18572 13396]

 [  786  1105]]


              precision    recall  f1-score   support

         0.0       0.96      0.58      0.72     31968
         1.0       0.08      0.58      0.13      1891

    accuracy                           0.58     33859
    macro avg      0.52      0.58      0.43     33859
    weighted avg   0.91      0.58      0.69     33859

**Train**

Train ROC AUC Score: 0.9995624122068659

[[68517    13]

 [   67 90778]]


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     68530
         1.0       1.00      1.00      1.00     90845

    accuracy                           1.00    159375
    macro avg      1.00      1.00      1.00    159375
    weighted avg   1.00      1.00      1.00    159375